---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: Start httpd server
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Allow http service
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
