---

- hosts: all
  become: true
  tasks:
  - name: Update Repository Index
    yum:
      update_cache: true
    when: ansible_distribution == "CentOS"
  - name: Install httpd package
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"
  - name: Start httpd server
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"
  - name: Allow port 80/tcp
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
      
  - name: Add php support for httpd
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS"
