---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for john
    tags: always
    authorized_key:
      user: john
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHygPXzji7FQO53zXAj2DMt3wYbEfzi9LmThv/ksR9j6 ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for CentOS servers
    tags: centos,php,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd server
    tags: httpd,centos
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Allow http service
    tags: httpd,centos
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled

  - name: change admin email address
    tags: httpd,centos
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: Restart httpd
    tags: httpd,centos
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: centos,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (CentOS)
    tags: mariadb,centos,db
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start mariadb server
    tags: db,mariadb,centos
    service:
      name: mariadb
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"
