---

- hosts: all
  become: true
  pre_tasks:

  - name: install update (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for CentOS servers
    tags: centos,php,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd server
    tags: httpd,centos
    systemd:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"

  - name: Allow http service
    tags: httpd,centos
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled

  - name: copy default html file for site
    tags: centos,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (CentOS)
    tags: mariadb,centos,db
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start mariadb server
    tags: db,mariadb,centos
    systemd:
      name: mariadb
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"
