- name: install apache and php for CentOS servers
  tags: centos,php,httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start httpd server
  tags: httpd,centos
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: Allow http service
  tags: httpd,centos
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: change admin email address
  tags: httpd,centos
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "CentOS"
  register: httpd

- name: Restart httpd
  tags: httpd,centos
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: centos,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
