- name: install apache and php for CentOS servers
  tags: centos,php,httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start httpd server
  tags: httpd,centos
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: Allow http service
  tags: httpd,centos
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  when: ansible_distribution == "CentOS"

- name: change admin email address
  tags: httpd,centos
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.io
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: copy default html file for site
  tags: centos,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
