- name: add ssh key for john
  tags: always
  authorized_key:
    user: john
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHygPXzji7FQO53zXAj2DMt3wYbEfzi9LmThv/ksR9j6 ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
